SELECT top 100 *
       FROM CBWG.SCH_SPRAWY_KREDYTOWE.T_SPRAWY_KREDYTOWE S
       INNER JOIN CBS.SCH_SLOWNIKI.T_PARAMETRY_ELEMENTOW P ON S.SKRE_CBS_ESLO_FSSKRE_ID = P.PELE_ESLO_ID
       INNER JOIN CBWG_ARCH.[SCH_ARCH].[ARCH_FILTR] F ON F.FIL_STATUS_SPRAWY_PARA_ID = P.PELE_PARA_ID AND F.FIL_CZY_AKTYWNY = 1
       WHERE S.DATA_PART IS NOT NULL
       AND (F.FIL_DATA_UTWORZENIA_SPRAWY IS NULL OR F.FIL_DATA_UTWORZENIA_SPRAWY >= S.DATA_PART)
       AND (
              --F.FIL_DATA_OSTATNIEJ_ZMIANY IS NULL OR 
              EXISTS(
                     SELECT * FROM CBWG.SCH_SPRAWY_KREDYTOWE.T_HISTORIE_SPRAW HS
                     INNER JOIN CBS.SCH_SLOWNIKI.T_PARAMETRY_ELEMENTOW HP ON HS.HSKR_CBS_ESLO_FSSKRE_ID = HP.PELE_ESLO_ID
                     INNER JOIN CBWG_ARCH.[SCH_ARCH].[ARCH_FILTR] HF ON HF.FIL_STATUS_SPRAWY_PARA_ID = HP.PELE_PARA_ID AND HF.FIL_CZY_AKTYWNY = 1      
                     WHERE HS.HSKR_SKRE_ID = S.SKRE_ID
                     AND DATEDIFF(MONTH, HS.HSKR_DATA_WEJSCIA, GETDATE()) >= HF.FIL_ILOSC_MIESIECY_OD_OSTATNIEJ_ZMIANY
                     AND (HF.FIL_DATA_OSTATNIEJ_ZMIANY IS NULL OR HF.FIL_DATA_OSTATNIEJ_ZMIANY >= HS.HSKR_DATA_WEJSCIA)
              )
        ) 

		--and skre_id in (1959712,1964832,1981196)