Use [CBWG]
Go
declare @skreId int =355  --2471890
select 
 s.[SKRE_ID]
,s.[SKRE_NUMER_WNIOSKU]
,(select [ESLO_NAZWA] from [CBS].[SCH_SLOWNIKI].[T_ELEMENTY_SLOWNIKOW] where [ESLO_ID] = s.[SKRE_CBS_ESLO_FSSKRE_ID]) [FSSKRE]
,w.[WDUC_ID]
,(select [ESLO_NAZWA] from [CBS].[SCH_SLOWNIKI].[T_ELEMENTY_SLOWNIKOW] where [ESLO_ID] = w.[WDUC_CBS_ESLO_STAW_ID]) [WDUC_STAW]
,(select [ESLO_NAZWA] from [CBS].[SCH_SLOWNIKI].[T_ELEMENTY_SLOWNIKOW] where [ESLO_ID] = k.[ULOG_CBS_ESLO_RWER_ID]) [RWER]
--,w.[WDUC_CBS_ESLO_FSZDAN_ID]
,(select [ESLO_NAZWA] from [CBS].[SCH_SLOWNIKI].[T_ELEMENTY_SLOWNIKOW] where [ESLO_ID] = w.[WDUC_CBS_ESLO_FSZDAN_ID]) [FSZDAN]
,k.[ULOG_ID]
,k.[ULOG_XML_IN]
,k.[ULOG_XML_OUT]
,(select [ESLO_NAZWA] from [CBS].[SCH_SLOWNIKI].[T_ELEMENTY_SLOWNIKOW] where [ESLO_ID] = k.[ULOG_CBS_ESLO_STAT_ID]) [ULOG_STAT]
,k.[DATA_UTWORZENIA]
,s.[SKRE_CZY_PREAPPROVED]
,s.[SKRE_CZY_KLIK]
from [SCH_SPRAWY_KREDYTOWE].[T_SPRAWY_KREDYTOWE] s
left join [SCH_SPRAWY_KREDYTOWE].[T_UCZESTNICY_SPRAW_KREDYTOWYCH] u on s.[SKRE_ID] = u.[USKR_SKRE_ID]
left join [SCH_KLIENCI].[T_WERSJE_DANYCH_UCZESTNIKOW] w on u.[USKR_ID] = w.[WDUC_USKR_ID]
left join [SCH_KLIENCI].[T_KREDUR_UCZESTNICY_LOG] k on w.[WDUC_ID] = k.[ULOG_WDUC_ID]
where 
        s.[SKRE_ID] = @skreId and
       (k.[ULOG_WDUC_ID] = w.[WDUC_ID] and k.[ULOG_CBS_ESLO_RWER_ID] in (select [ESLO_ID] from [CBS].[SCH_SLOWNIKI].[T_ELEMENTY_SLOWNIKOW] where [ESLO_KOD] in ('DUDEF', 'CKK','CSCUS')))
       --k.[DATA_UTWORZENIA] < '2019-01-20 10:22:36.070'
       --and s.[SKRE_CZY_PREAPPROVED] = 1
order by [ULOG_ID] desc
