
USE CBUZYTKOWNIKOW

DECLARE @imiê varchar(100)
DECLARE	@nazwisko varchar(100)
DECLARE @login varchar(100)
DECLARE @email varchar(100)
DECLARE @login_kopia varchar(100)

SET @imiê  ='Ma³gorzata'
SET @nazwisko ='Ska³ecka'
SET @login = 'm.skalecka'
SET @email = 'Malgorzata.Skalecka@gnb.pl'

set @login_kopia = 'a.kujawowicz'


INSERT INTO CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY
(
    --UZYT_ID - this column value is auto-generated
    UZYT_SID,
    UZYT_IMIE,
    UZYT_NAZWISKO,
    UZYT_LOGIN,
    UZYT_DOMENA,
    UZYT_EMAIL,
    UZYT_TYP,
    UZYT_STATUS,
    UZYT_DATA_UTWORZENIA,
    UZYT_LOGIN_TWORZACEGO,
    UZYT_DATA_MODYFIKACJI,
    UZYT_LOGIN_MODYFIKUJACEGO,
    UZYT_WZOR_PODPISU,
    --UZYT_LOGIN_PELNY - this column value is auto-generated
    UZYT_PESEL,
    UZYT_CBS_ESLO_PLEC_ID,
    UZYT_DATA_URODZENIA,
    UZYT_CBS_ESLO_REGIO_ID,
    UZYT_CBS_ESLO_MKREG_ID,
	UZYT_PIERWOTNY_ID
)
VALUES
(
    -- UZYT_ID - int
    NEWID(), -- UZYT_SID - varchar
    @imiê, -- UZYT_IMIE - varchar
    @nazwisko, -- UZYT_NAZWISKO - varchar
    @login, -- UZYT_LOGIN - varchar
    'GB', -- UZYT_DOMENA - varchar
    @email, --@login + '@GetinBank.pl', -- UZYT_EMAIL - varchar
    0, -- UZYT_TYP - tinyint
    1, -- UZYT_STATUS - bit
    GETDATE(), -- UZYT_DATA_UTWORZENIA - datetime
    SUSER_NAME(), -- UZYT_LOGIN_TWORZACEGO - varchar
    NULL, -- UZYT_DATA_MODYFIKACJI - datetime
    NULL, -- UZYT_LOGIN_MODYFIKUJACEGO - varchar
    NULL, -- UZYT_WZOR_PODPISU - varbinary
	NULL, -- UZYT_PESEL - varchar
    (CASE WHEN (right(@imiê,1) IN ('a','A'))
		then 645
		else  646
	
	end
	), -- UZYT_CBS_ESLO_PLEC_ID - int
    '1990-05-04 14:38:30', -- UZYT_DATA_URODZENIA - datetime
    null, -- UZYT_CBS_ESLO_REGIO_ID - int
    null -- UZYT_CBS_ESLO_MKREG_ID - int
	,(SELECT max(tu1.UZYT_ID)+1 from CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY tu1 )--WHERE tu1.UZYT_LOGIN=@login_kopia)
)


INSERT INTO CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY_ROLE
SELECT 
	(SELECT UZYT_ID FROM CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY tu WHERE tu.UZYT_LOGIN=@login AND tu.UZYT_STATUS=1),
	UZRO_ROLE_ID
	from CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY_ROLE ur
WHERE ur.UZRO_UZYT_ID=(SELECT tu1.UZYT_ID from CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY tu1 WHERE tu1.UZYT_LOGIN=@login_kopia AND tu1.UZYT_STATUS=1)


INSERT INTO CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY_PODMIOTY
SELECT
	(SELECT UZYT_ID FROM CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY tu WHERE tu.UZYT_LOGIN=@login AND tu.UZYT_STATUS=1),
	up.UPOD_CBP_PODM_ID,
	up.UPOD_CBS_ESLO_TRUZ_ID
from CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY_PODMIOTY up
WHERE up.UPOD_UZYT_ID=(SELECT tu1.UZYT_ID from CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY tu1 WHERE tu1.UZYT_LOGIN=@login_kopia AND tu1.UZYT_STATUS=1)

INSERT INTO CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY_CAK
SELECT
	(SELECT UZYT_ID FROM CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY tu WHERE tu.UZYT_LOGIN=@login AND tu.UZYT_STATUS=1),
	UCAK_CBS_CAK_ID

	from 
	CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY_CAK uc
	WHERE uc.UCAK_UZYT_ID=(SELECT tu1.UZYT_ID from CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY tu1 WHERE tu1.UZYT_LOGIN=@login_kopia AND tu1.UZYT_STATUS=1)


INSERT INTO CBUZYTKOWNIKOW.dbo.T_ATRYBUTY_UZYTKOWNIKOW
	SELECT 
	   --[AUZY_UZYT_ID]
	  (SELECT UZYT_ID FROM CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY tu WHERE tu.UZYT_LOGIN=@login AND tu.UZYT_STATUS=1)
      ,[AUZY_TAUZ_ID]
      ,[AUZY_WARTOSC_D]
      ,[AUZY_WARTOSC_N]
      ,[AUZY_WARTOSC_Z]
      ,[AUZY_WARTOSC_L]
      ,[AUZY_CBS_ESLO_STAT_ID]
      ,[AUZY_DATA_UTWORZENIA]
      ,[AUZY_UTWORZYL]
      ,[AUZY_DATA_MODYFIKACJI]
      ,[AUZY_MODYFIKOWAL]
      ,[AUZY_DATA_OD]
      ,[AUZY_DATA_DO]
   FROM [CBUZYTKOWNIKOW].[dbo].[T_ATRYBUTY_UZYTKOWNIKOW] as auzy
   WHERE auzy.AUZY_UZYT_ID = (SELECT tu1.UZYT_ID from CBUZYTKOWNIKOW.dbo.T_UZYTKOWNICY tu1 WHERE tu1.UZYT_LOGIN=@login_kopia AND tu1.UZYT_STATUS=1)
