select 
       skre.SKRE_NUMER_WNIOSKU as "Numer wniosku"
       ,KRED.[KRED_KWOTA_NETTO] as "Kwota netto wnioskowanego kredytu"
       ,OfKred.[OKRE_CZY_ZAZNACZONA] as "Czy zaznaczono"
       ,ofer.OFER_NAZWA as "Nazwa oferty"
	   ,[WOK_CBS_ESLO_STAW_ID]
	  ,WDUC.[DATA_UTWORZENIA]
	  ,KRED.[KRED_CZY_WYBRANY]
      ,KRED.[KRED_CZY_ZAPREZENTOWANY]
      ,KRED.[KRED_CZY_PRZELICZONY]
	  ,[DOSO_IMIE_CZ1]
      ,[DOSO_IMIE_CZ2]
      ,[DOSO_NAZWISKO_CZ1]
	  ,[KUCZ_ID]
      ,[KUCZ_KRED_ID]
      ,[KUCZ_WDUC_ID]
      ,[KUCZ_MAX_KWOTA_BRUTTO]
      ,[KUCZ_MAX_RATA]
      ,[KUCZ_MAX_RATA_DTR]
      ,[KUCZ_MAX_RATA_STANDARD]
      ,[KUCZ_SUM_DOCHOD_NETTO]
      ,[KUCZ_MAX_RATA_GUS]
      ,[KUCZ_MAX_RATA_DTR_GUS]
      ,[KUCZ_MAX_RATA_STANDARD_GUS]
      ,[KUCZ_SUM_DOCHOD_NETTO_GUS]
      ,[KUCZ_MAX_KWOTA_NETTO_ZDOLNOSC]
      ,[KUCZ_MAX_KWOTA_NETTO_DOCHODY]
      ,[KUCZ_MAX_KWOTA_NETTO_SCORING]
      ,[KUCZ_MAX_KWOTA_NETTO_MAILING]
      ,[KUCZ_MAX_KWOTA_NETTO_RACHUNEK]
      ,[KUCZ_MAX_KWOTA_NETTO_OFERTA]
      ,[KUCZ_MAX_RATA_OSWIADCZENIE]
      ,[KUCZ_MAX_RATA_DTR_OSWIADCZENIE]
      ,[KUCZ_MAX_RATA_STANDARD_OSWIADCZENIE]
      ,[KUCZ_MAX_RATA_ZDOLNOSC]
      ,[KUCZ_SUM_DOCHOD_NETTO_OSWIADCZENIE]
      ,[KUCZ_SUMA_ZAANGAZOWANIA_W_PROCEDURZE_UPROSZCZONEJ]
      ,[KUCZ_CZY_WSPOLMALZONEK_WYMAGANY]
      ,[KUCZ_LIMIT_BEZ_ZGODY_MALZONKA]
      ,[KUCZ_CZY_WYMAGANE_DOK_POTW_STAN_CYWI]
       

from CBWG.SCH_SPRAWY_KREDYTOWE.T_SPRAWY_KREDYTOWE as skre  
JOIN CBWG.[SCH_SPRAWY_KREDYTOWE].[T_WERSJE_OFERT_KREDYTOW] as WOK on WOK.[WOK_SKRE_ID]=skre.[SKRE_ID]
JOIN CBWG.[SCH_SPRAWY_KREDYTOWE].[T_OFERTY_KREDYTOWE] as OfKred on OfKred.[OKRE_WOK_ID]=WOK.[WOK_ID]
JOIN CBWG.[SCH_SPRAWY_KREDYTOWE].[T_KREDYTY] as KRED on KRED.[KRED_OKRE_ID]=OfKred.[OKRE_ID]
JOIN CBWG.[SCH_SPRAWY_KREDYTOWE].[T_KREDYT_UCZESTNICY] as KredUcze on KredUcze.[KUCZ_KRED_ID]=KRED.[KRED_ID]

JOIN CBWG.SCH_SPRAWY_KREDYTOWE.T_UCZESTNICY_SPRAW_KREDYTOWYCH as uskr on uskr.USKR_SKRE_ID = skre.SKRE_ID 
JOIN CBWG.SCH_KLIENCI.T_WERSJE_DANYCH_UCZESTNIKOW as wduc on wduc.WDUC_USKR_ID = uskr.USKR_ID 
JOIN CBWG.[SCH_KLIENCI].[T_DANE_OSOBOWE] as doso on wduc.[WDUC_DOSO_ID]=doso.[DOSO_ID] 
JOIN CBWG.[SCH_KLIENCI].[T_DANE_POZOSTALE] as dpoz on wduc.[WDUC_DPOZ_ID]=dpoz.[DPOZ_ID] 
join CBO.[SCH_OFERTY].[T_OFERTY] as ofer on ofer.OFER_ID = OfKred.[OKRE_CBO_OFER_ID]


where skre.[SKRE_NUMER_WNIOSKU] = 'F/2018/110804'  
/*and OfKred.[OKRE_CZY_ZAZNACZONA] <>0*/ and WOK.[WOK_CBS_ESLO_STAW_ID]=18


