USE CBWG
go

select OKRE.OKRE_ID, 
             OFER.[OFER_NAZWA]
from
             [SCH_SPRAWY_KREDYTOWE].[T_SPRAWY_KREDYTOWE] SKRE

join  [SCH_SPRAWY_KREDYTOWE].[T_WERSJE_OFERT_KREDYTOW] WOK
             on WOK.WOK_SKRE_ID = SKRE.SKRE_ID

join  [SCH_SPRAWY_KREDYTOWE].[T_OFERTY_KREDYTOWE] OKRE
             on OKRE.OKRE_WOK_ID = WOK.WOK_ID


join  CBO.[SCH_OFERTY].[T_OFERTY] OFER
             on OFER.OFER_ID = OKRE.OKRE_CBO_OFER_ID

 join  CBS.[SCH_SLOWNIKI].[T_ELEMENTY_SLOWNIKOW] ELEM 
             on OFER.OFER_CBS_ESLO_TOFE_ID = ELEM.ESLO_ID

where 

SKRE.SKRE_ID = 190933
and (OKRE_CZY_PETLA_OSWIADCZENIE = 1 OR OKRE_CZY_PETLA_OSWIADCZENIE is NULL)



and WOK.[WOK_CBS_ESLO_STAW_ID] = 18
and ELEM.ESLO_NAZWA = N'Karta kredytowa'
ORDER BY OFER_NAZWA DESC
