use cbwg
declare @skre_id int = 4284

--select SKRE_NUMER_WNIOSKU from cbwg.SCH_SPRAWY_KREDYTOWE.T_SPRAWY_KREDYTOWE where SKRE_ID = @skre_id


select top 100 -- WZBI.WZBI_ID [Wyniki zbiorcze], 
--WAUT_CZY_WERYFIKACJA_DBO,
-- wzbi.WZBI_CBS_ESLO_STAW_ID 'wzbi staw',
DPOZ_SUMA_ZAANGAZOWANIA_W_NIEZAB_RZECZ,
DPOZ.DPOZ_CBS_ESLO_FSKLI_ID,
DPOZ.DPOZ_ID,
waut_id,
WAUT_RWER.ESLO_NAZWA,
waut_dane_wynikowe,
       WZUC.WZUC_ID, 
       wzuc.WZUC_CBS_ESLO_STAW_ID 'wzuc staw',
         WAUT.WAUT_Id 'wer auto',
         WZBI_FWWAUT.ESLO_ID, 
         WZBI_FWWAUT.ESLO_KOD, 
         WZBI_FWWAUT.ESLO_NAZWA,
          WZUC_FWWAUT.ESLO_KOD, 
          WZUC_FWWAUT.ESLO_NAZWA, 
 WAUT_FWWAUT.ESLO_KOD, 
 WAUT.WAUT_ID,
WAUT_FWWAUT.ESLO_NAZWA,
WAUT.WAUT_CBS_ESLO_RWER_ID,
WAUT_RWER.ESLO_KOD,
WAUT_RWER.ESLO_ID,
SKRE.SKRE_NUMER_WNIOSKU,
SKRE.SKRE_ID
,WAUT.*
,WZUC.*

from [SCH_SPRAWY_KREDYTOWE].[T_SPRAWY_KREDYTOWE] SKRE
left join [SCH_ZADANIA].[T_WYNIKI_ZBIORCZE] WZBI on WZBI.WZBI_SKRE_ID = SKRE.SKRE_ID
left join [SCH_ZADANIA].[T_WYNIKI_UCZESTNIKOW] WUCZ on WUCZ.WUCZ_WZBI_ID = WZBI.WZBI_ID
left join [SCH_ZADANIA].[T_WYNIKI_ZBIORCZE_UCZESTNIKOW] WZUC on WZUC.WZUC_ID = WUCZ.WUCZ_WZUC_ID
left join [SCH_ZADANIA].[T_WYNIKI_WERYFIKACJI_AUTOMAT] WWAU on WWAU_WZUC_ID = WZUC.WZUC_ID
left join [SCH_ZADANIA].[T_WERYFIKACJE_AUTOMATYCZNE] WAUT on WAUT.WAUT_ID = WWAU.WWAU_WAUT_ID
left join [CBS].SCH_SLOWNIKI.T_ELEMENTY_SLOWNIKOW WZUC_FWWAUT on WZUC_FWWAUT.ESLO_ID = WZUC.WZUC_CBS_ESLO_FWWAUT_ID
left join [CBS].SCH_SLOWNIKI.T_ELEMENTY_SLOWNIKOW WZBI_FWWAUT on WZBI_FWWAUT.ESLO_ID = WZBI.WZBI_CBS_ESLO_FWWAUT_ID
left join [CBS].SCH_SLOWNIKI.T_ELEMENTY_SLOWNIKOW WAUT_FWWAUT on WAUT_FWWAUT.ESLO_ID = WAUT.WAUT_CBS_ESLO_FWWAUT_ID
left join [CBS].SCH_SLOWNIKI.T_ELEMENTY_SLOWNIKOW WAUT_RWER on WAUT_RWER.ESLO_ID = WAUT.WAUT_CBS_ESLO_RWER_ID
left join SCH_SPRAWY_KREDYTOWE.T_UCZESTNICY_SPRAW_KREDYTOWYCH USKR on WZUC_USKR_ID = USKR_ID
left join SCH_KLIENCI.T_WERSJE_DANYCH_UCZESTNIKOW WDUC on WDUC_USKR_ID = USKR_ID
left join SCH_KLIENCI.T_DANE_POZOSTALE DPOZ on WDUC_DPOZ_ID = DPOZ_ID

where
-- WAUT_RWER.ESLO_NAZWA like 'Listy sankcyjne/PEP'
     WAUT_RWER.ESLO_NAZWA = 'CBKB'  and
skre.Skre_id = @skre_id
       and WZBI.WZBI_CBS_ESLO_STAW_ID = 18
       order by WZBI.WZBI_ID desc
