SELECT  SKRE.[SKRE_ID]
	  ,USKR.[USKR_SKRE_ID]
	  ,USKR.[USKR_ID]
	  ,WDUC.[WDUC_USKR_ID]
	  ,WDUC.[WDUC_ID]
	  ,[DPOZ_CBS_ESLO_FSKLI_ID]
	  ,[DPOZ_ID]
	  ,[DPOZ_KLIENT_WSPOLPRACUJACY_OKRES]
	 
		FROM [CBWG].[SCH_SPRAWY_KREDYTOWE].[T_SPRAWY_KREDYTOWE] SKRE
  JOIN [CBWG].[SCH_SPRAWY_KREDYTOWE].[T_UCZESTNICY_SPRAW_KREDYTOWYCH] AS USKR on SKRE.[SKRE_ID] = USKR.[USKR_SKRE_ID]
  JOIN [CBWG].[SCH_KLIENCI].[T_WERSJE_DANYCH_UCZESTNIKOW] AS WDUC ON USKR.[USKR_ID]=WDUC.[WDUC_USKR_ID]
  JOIN [CBWG].[SCH_KLIENCI].[T_DANE_POZOSTALE] AS DPOZ ON DPOZ.DPOZ_ID=[WDUC_DPOZ_ID]
  where USKR.[USKR_SKRE_ID]=3816

  --update [CBWG].[SCH_KLIENCI].[T_DANE_POZOSTALE]
  --set [DPOZ_CBS_ESLO_FSKLI_ID]=5803
  --where [DPOZ_ID]=3341